networks:
  inceptionet:
    driver: bridge

services:
  nginx:
    build: ./requirements/nginx
    container_name: my_nginx
    env_file:
      - .env
    networks:
      - inceptionet
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - inception_www:/var/www/html
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: my_wordpress
    env_file:
      - .env
    networks:
      - inceptionet
    volumes:
      - inception_www:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: my_mariadb
    env_file:
      - .env
    networks:
      - inceptionet
    volumes:
      - inception_db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always


volumes:
  inception_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fheid/data/inception_db

  inception_www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fheid/data/inception_www