networks:
  inceptionet:
    driver: bridge

services:
  nginx:
    build: ./requirements/nginx
    container_name: my_nginx
    env_file:
      - .env
    networks:
      - inceptionet
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - inception_www:/var/www/html
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: my_wordpress
    env_file:
      - .env
    networks:
      - inceptionet
    volumes:
      - inception_www:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: my_mariadb
    env_file:
      - .env
    networks:
      - inceptionet
    volumes:
      - inception_db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  redis:
    build: ./requirements/bonus/redis
    container_name: my_redis
    env_file:
      - .env
    networks:
      - inceptionet
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    container_name: my_adminer
    env_file:
      - .env
    networks:
      - inceptionet
    restart: always

  website:
    build: ./requirements/bonus/website
    container_name: my_website
    ports:
      - "8070:8070"
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    container_name: my_ftp
    env_file:
      - .env
    networks:
      - inceptionet
    ports:
      - "21:21"
      - "64000-64321:64000-64321"
    volumes:
      - inception_www:/var/www/html
    restart: always

  grafana:
    build: ./requirements/bonus/grafana
    container_name: my_grafana
    env_file:
      - .env
    networks:
      - inceptionet
    ports:
      - "3000:3000"
    volumes:
      - inception_grafana:/var/lib/grafana
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  inception_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fheid/data/inception_db

  inception_www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fheid/data/inception_www

  inception_grafana:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fheid/data/inception_grafana